import "./globals.css";

import { Climate_Crisis } from "next/font/google";
import type { Metadata } from "next";

const climateCrisis = Climate_Crisis({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio Matias Querejeta",
  description: "Generated by Matias Querejeta",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='bg-slate-800' lang="en">
      <body className={climateCrisis.className} >{children}</body>
    </html>
  );
}
